/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PokemonsIndexImport } from './routes/pokemons/index'
import { Route as PokemonsIdImport } from './routes/pokemons/$id'
import { Route as PokemonsMovesIdImport } from './routes/pokemons/moves.$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonsIndexRoute = PokemonsIndexImport.update({
  id: '/pokemons/',
  path: '/pokemons/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonsIdRoute = PokemonsIdImport.update({
  id: '/pokemons/$id',
  path: '/pokemons/$id',
  getParentRoute: () => rootRoute,
} as any)

const PokemonsMovesIdRoute = PokemonsMovesIdImport.update({
  id: '/pokemons/moves/$id',
  path: '/pokemons/moves/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/pokemons/$id': {
      id: '/pokemons/$id'
      path: '/pokemons/$id'
      fullPath: '/pokemons/$id'
      preLoaderRoute: typeof PokemonsIdImport
      parentRoute: typeof rootRoute
    }
    '/pokemons/': {
      id: '/pokemons/'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof PokemonsIndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemons/moves/$id': {
      id: '/pokemons/moves/$id'
      path: '/pokemons/moves/$id'
      fullPath: '/pokemons/moves/$id'
      preLoaderRoute: typeof PokemonsMovesIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pokemons/$id': typeof PokemonsIdRoute
  '/pokemons': typeof PokemonsIndexRoute
  '/pokemons/moves/$id': typeof PokemonsMovesIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pokemons/$id': typeof PokemonsIdRoute
  '/pokemons': typeof PokemonsIndexRoute
  '/pokemons/moves/$id': typeof PokemonsMovesIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pokemons/$id': typeof PokemonsIdRoute
  '/pokemons/': typeof PokemonsIndexRoute
  '/pokemons/moves/$id': typeof PokemonsMovesIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/about'
  | '/pokemons/$id'
  | '/pokemons'
  | '/pokemons/moves/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/pokemons/$id' | '/pokemons' | '/pokemons/moves/$id'
  id:
  | '__root__'
  | '/'
  | '/about'
  | '/pokemons/$id'
  | '/pokemons/'
  | '/pokemons/moves/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PokemonsIdRoute: typeof PokemonsIdRoute
  PokemonsIndexRoute: typeof PokemonsIndexRoute
  PokemonsMovesIdRoute: typeof PokemonsMovesIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PokemonsIdRoute: PokemonsIdRoute,
  PokemonsIndexRoute: PokemonsIndexRoute,
  PokemonsMovesIdRoute: PokemonsMovesIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/pokemons/$id",
        "/pokemons/",
        "/pokemons/moves/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/pokemons/$id": {
      "filePath": "pokemons/$id.tsx"
    },
    "/pokemons/": {
      "filePath": "pokemons/index.tsx"
    },
    "/pokemons/moves/$id": {
      "filePath": "pokemons/moves.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
